---
title: "Import Export mismatch"
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---

```{r packages, echo=FALSE, warning=FALSE, message=FALSE}
library(tradeflows)
library(knitr)
opts_knit$set(root.dir="../..") # file paths are relative to the root of the project directory
library(dplyr)
library(ggplot2)
library(tidyr)
``` 


# Description of the issue

In 2018 there was an update to the Comext data structure.
The update requires a modification of the database structure and of
the way units are dealt with in the cleaning functions. 


## Sample code
```{r}
# Connect to the database
con <- RMariaDB::dbConnect(RMariaDB::MariaDB(), dbname = "tradeflows")
# Load data for product 44079910
# The issue is within that code:
dtf <- loadcomext1product(con,
                          productanalysed = "44071091",
                          tablearchive = "raw_comext_monthly_2016S1",
                          tablerecent = "raw_comext_monthly")
# which itself calls `eutradeflows::addunit2tbl`
# The problem is that the unit code is already there. 

head(dtf)
unique(dtf$year)
```

## InNvestigate

```{r}

```

