---
title: "Learning to load data from MySQL"
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---


```{r packages, echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
opts_knit$set(root.dir="../..") # file paths are relative to the root of the project directory
library(tradeflows)
library(dplyr)
library(RMySQL)
``` 

## Connection using dplyr, SELECT only

* [insert using dplyr](http://stackoverflow.com/questions/26568182/is-it-possible-to-insert-add-a-row-to-a-sqlite-db-table-using-dplyr-package)
```{r insertdplyr, eval=FALSE}
tdb <- src_mysql(user="tradeflows", host="localhost",
                       password="tradeflows", dbname="tradeflows")
# Create table
copy_to(tdb, swdhead, "enddata2", temporary = FALSE)
# Insert into the new table
db_insert_into(con = tdb$con, table = "enddata2", fields = swdhead) 
```

```{r}
```

## Connection using RMySQL connection, SELECT and 
Source of the package : [RMySQL](https://github.com/jeffreyhorner/RMySQL)

Following developments inspired by :

* [a finnish blog](http://gettinggeneticsdone.blogspot.fi/2011/12/query-mysql-database-from-r-using.html).
* [a question on stackoverflow](http://stackoverflow.com/questions/5431961/connect-to-mysql-database-with-rmysql)

### SELECT
```{r rmysql_select}
tdb2 <- dbConnect(MySQL(), user="tradeflows", host="localhost",
                       password="tradeflows", dbname="tradeflows")
dbListTables(tdb2)
querytradedb <-  function(...) dbGetQuery(tdb2, ...)
swdhead <- querytradedb("SELECT * FROM raw_trade_data LIMIT 10;")
```


### CREATE
```{r eval=FALSE}
querytradedb("CREATE TABLE enddata LIKE tradeflows.raw_trade_data;")
dbListTables(tdb2)
```

### INSERT
```{r rmysql_insert, eval=FALSE}
dbGetQuery(DB, "INSERT into SELECT * FROM raw_trade_data LIMIT 10;")

```



