---
title: "Country name encoding in utf-8 only"
author: "Paul Rougieux"
date: "26/02/2015"
output:
  pdf_document:
    toc: yes
    toc_depth: 3
---


```{r packages, echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
opts_knit$set(root.dir="../../..") # file paths are relative to the root of the project directory
opts_chunk$set(echo=TRUE, warning=FALSE)
library(tradeflows)
library(dplyr)
library(ggplot2)
library(reshape2)
``` 



## Simo's message from August 10
Simo:

```{r}
itto <- classificationitto
round(itto$productcodecomtrade / 10000)


itto <- itto %>% 
    mutate(twodigit = round(itto$productcodecomtrade / 10000),
           fourdigit =  round(itto$productcodecomtrade / 100))

fourdigitalone <- itto %>% filter(twodigit == 0)
fourdigitalone <- fourdigitalone$productcodecomtrade
# They are only present at the 4 digit level
fourdigitalone[!fourdigitalone %in% itto$fourdigit]

# They are present both at the 4 and T digit level
fourdigitalone[fourdigitalone %in% itto$fourdigit]

```

