---
title: " Excel files containing prices and conversion factors"
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---


```{r packages, echo=FALSE, warning=FALSE, message=FALSE}
library(tradeflows)
library(knitr)
opts_knit$set(root.dir="../..") # file paths are relative to the root of the project directory
library(dplyr)
``` 

# Time taken by clean2excel
```{r}
swd99 <- readdbproduct(440799, "raw_flow_yearly")
system.time(clean(swd99))
#    user  system elapsed 
#   8.764   0.000   8.726 
system.time(cleandb2excel(440799))
#   user  system elapsed 
#  23.568   0.264  16.481 
```


# List of Excel files containing prices and conversion factors

```{r echo=FALSE, warning=FALSE}
tfdb <- readdbtbl("validated_flow_yearly")
codeunit <- tfdb %>% 
    select(productcode,unit) %>% 
    distinct() %>%
    collect()
jfsq <- classificationitto %>%
    select(productcode = productcodecomtrade,
           jfsq1name) %>% distinct()
codeunit %>% 
    left_join(jfsq) %>%
    select(jfsq1name, unit, productcode) %>%
    arrange(jfsq1name) %>%
    mutate(excel = paste0(productcode,".xlsx")) %>%
    kable()
```
