---
title: "Overview Report Issue"
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---


```{r packages, echo=FALSE, warning=FALSE, message=FALSE}
library(tradeflows)
library(knitr)
opts_knit$set(root.dir="../..") # file paths are relative to the root of the project directory
library(dplyr)
``` 


# Issue November 2015
[Issue 14](https://bitbucket.org/paul4forest/tradeflows/issues/14/errors-in-the-overview-reports) reported by Janne, concerns 
issues when overview report are generated for one year only.

```{r}
# Data only
tfdataissue <- createoverviewreport("France",
                                    beginyear=2012, endyear=2014,
                                    dataonly=TRUE)
# Report
createoverviewreport("China",beginyear=2012, endyear=2012,
                     template="overviewtradevalue.Rmd",
                     outputdir="reports/something/",
                     tableread="validated_flow_yearly", jfsqlevel=2)
```

# Missing jfsq names

```{r}
productitto <- readdbtbl("product_work") %>% 
         filter(nomenclature == "HS12") %>%
         select(product = name_short, productcode = code) 
productitto %>%     explain()

productitto2 <- readdbtbl("product_work") %>% 
    select(product = name_short, productcode = code) %>%
    distinct()
productitto2 %>%     explain()
```
