---
title: "Forest produts trade in `r reporterinreport`"
author: "Paul Rougieux"
date: "12/05/2015"
output: 
  pdf_document:
    toc: yes
---


```{r library, echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(tradeflows)
library(knitr)
library(ggplot2)
options(digits = 4) #  Number of digits in knitr tables
opts_chunk$set(echo=FALSE, message=FALSE)
```



```{r development, eval=FALSE, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
######### #
# ! This chunk is used for development purposes only, keep eval=FALSE.
######### #
# Test countries: Cameroon, Ghana, Indonesia
#----------------------------------------------------------

```



```{r summary}
tfsummarised <- tfdata %>%
    group_by(year, reporter, partner, partnercode, flow, product) %>%
    summarise(tradevalue = sum(tradevalue)) %>%
    collect()

```


```{r preparedata}
# 100 largest trade flows
largetf <- tfdata %>% filterworldeu28 %>% data.frame() %>% # remove grouping
    arrange(desc(tradevalue)) %>% head(100)

# 10 largest partners for the dataframe currently in use in the report
#' @param dtf data frame of trade flow data
#' @param n number of parnters to select
#' @param product_ character vector of product names, when NULL, query all products
#' @examples
#'\dontrun{
#' largepartners()
#' largepartners(c("LOGS","SAWNWOOD"))
#' }
largepartners <- function(product_=NULL, dtf = tfsummarised, n = 10){
    if (!is.null(product_)){
        dtf <- filter(dtf, product %in% product_) 
    }
    dtf <- dtf %>%
        filterworldeu28() %>% 
        group_by(flow, partner, partnercode) %>% 
        summarise(tradevalue = sum(tradevalue)) %>%
        data.frame() %>% # remove grouping
        arrange(desc(tradevalue)) %>% 
        select(partner, partnercode) %>% unique %>% head(n) # Could add flow here
    return(dtf)
}
```


```{r productdescription}
#' Product description
#' Use:
#' description(c(440799, 440795))
description <- function(productcodes){
    descr <- classificationcomtrade$HS %>%
        filter(productcode %in% productcodes) 
    # Individual codes and description remove product code if its
    # at the begining of the description
    if (sum(as.character(descr$productcode) !=
        substring(descr$description, 1, 6))==0){
        descr$description <- substring(descr$description,7)
        }
    for(code in descr$productcode){
        cat("\n\n__",code,":__ ", sep="")
        cat(descr$description[descr$productcode == code])
    }
}
```


\newpage

## Logs 
```{r results='asis', fig.height=7, fig.width=12}
#' @param product_ the itto name of a product
productplot <- function(product_){
    # Prepare this object first otherwise query is very slow
    partnercodes <- largepartners(product_)$partnercode    
    # Data
    dtf <- filter(tfdata, product == product_ & 
                      partnercode %in% partnercodes) %>%
        mutate(partner = stringr::str_wrap(partner, width = 14) )
    p <- ggplot(dtf,
                aes(x = as.numeric(year),
                    y = tradevalue,
                    fill = as.factor(productcode))) +
        geom_bar(stat="identity") +
        ylab("Trade value in  US dollars") +
        theme(legend.position= "bottom") +
        scale_x_continuous(breaks = c(2010,2012)) +
        ggtitle(paste("Largest ", product_, " flows reported by", reporterinreport)) +
        facet_grid(flow + reporter ~ partner, scales="free_y") + 
        guides(fill=guide_legend(nrow=2,byrow=TRUE))
    try(print(p))
    try(description(unique(dtf$productcode)))
}
 
productplot("LOGS")
```

\newpage

## Sawnwood
```{r results='asis', fig.height=7, fig.width=12}
productplot("SAWNWOOD")
```


\newpage

## Furniture

```{r results='asis', fig.height=7, fig.width=12}
productplot("WOODEN FURNITURE")

## Other products groups that could be added for separate plots
## See report on Indonesia's industry
## Furniture
## Wood panels
## Pulp and paper
```


## All products
```{r fig.height=17, fig.width=12}
partnercodes <- largepartners()$partnercode
# filter(tfdata, partner %in% largetf$partner)
ggplot(filter(tfsummarised, partnercode %in% partnercodes),
       aes(x = as.numeric(year), y = tradevalue/1e6,
                       fill = as.factor(product))) +
    geom_bar(stat="identity") +
    ylab("Trade value in million US dollars") +
    theme(legend.position= "bottom") +
    scale_x_continuous(breaks = c(2010,2012)) +
    ggtitle(paste("Largest wood products flows reported by", reporterinreport)) +
    facet_grid(flow + reporter ~ partner) + 
    guides(fill=guide_legend(ncol=1,byrow=TRUE))

message("place country names over 2 lines if necessary")
# http://stackoverflow.com/questions/9052650/ggplot2-splitting-facet-strip-text-into-two-lines
# Using stringr::str_wrap
# stringr::str_wrap("lkj lkj lkjlkj lkj lkj ", width = 20) 
# Or with base functions, without the stringr package
# paste(strwrap("lkj lkj lkjlkj lkj lkj ", width = 20), collapse="\n")

# Optionally 
# Make the same plot with flows reported from those countries

```



```{r eval=FALSE}
### Trade between `r reporterinreport` and the EU
# EU is a reporter in the database, but not a partner.
ggplot(filter(tfdata, partner == "EU28"),
       aes(x = as.numeric(year), y = tradevalue/1e6,
                       fill = as.factor(product))) +
    geom_bar(stat="identity") +
    scale_x_continuous(breaks = c(2010,2012)) +
    ggtitle("100 Largest wood products import flows reported by the EU with China") +
    facet_grid(flow + reporter ~ partner) + 
    ylab("Trade value in million US dollars") +
    theme(legend.position= "bottom") +
    guides(fill=guide_legend(nrow=4,byrow=TRUE))
```



